# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Apr  1 13:19:09 2022
# ------------------------------------------------

package:
  name: sniffio
  version: 1.2.0
source:
  sha256: c4666eecec1d3f50960c6bdf61ab7bc350648da6c126e3cf6898d8cd4ddcd3de
  url: https://pypi.io/packages/source/s/sniffio/sniffio-1.2.0.tar.gz
build:
  number: '3'
  script: 'D:\\bld\\sniffio_1648819427747\\_h_env\\python.exe -m pip install . --no-deps
    --ignore-installed --no-cache-dir -vvv '
  string: py38haa244fe_3
requirements:
  build: []
  host:
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2021.10.8 h5b45459_0
    - libffi 3.4.2 h8ffe710_5
    - libzlib 1.2.11 h8ffe710_1014
    - openssl 3.0.2 h8ffe710_1
    - pip 22.0.4 pyhd8ed1ab_0
    - python 3.8.13 hcf16a7b_0_cpython
    - python_abi 3.8 2_cp38
    - setuptools 61.3.0 py38haa244fe_0
    - sqlite 3.37.1 h8ffe710_0
    - tk 8.6.12 h8ffe710_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_6
    - vs2015_runtime 14.29.30037 h902a5da_6
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h62dcd97_1
  run:
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
test:
  imports:
    - sniffio
    - sniffio._tests
about:
  doc_url: https://sniffio.readthedocs.io
  home: https://github.com/python-trio/sniffio
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.APACHE2
  summary: Sniff out which async library your code is running under
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - nicoddemus
