# This file created by conda-build 3.22.0
# ------------------------------------------------

package:
  name: uvicorn
  version: 0.18.3
source:
  sha256: 9a66e7c42a2a95222f76ec24a4b754c158261c4696e683b9dadc72b590e0311b
  url: https://pypi.io/packages/source/u/uvicorn/uvicorn-0.18.3.tar.gz
build:
  entry_points:
    - uvicorn = uvicorn.main:main
  number: 0
  string: py38haa244fe_0
requirements:
  host:
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2022.6.15 h5b45459_0
    - libffi 3.4.2 h8ffe710_5
    - libsqlite 3.39.2 h8ffe710_1
    - libzlib 1.2.12 h8ffe710_2
    - openssl 3.0.5 h8ffe710_1
    - pip 22.2.2 pyhd8ed1ab_0
    - python 3.8.13 hcf16a7b_0_cpython
    - python_abi 3.8 2_cp38
    - setuptools 65.2.0 py38haa244fe_0
    - sqlite 3.39.2 h8ffe710_1
    - tk 8.6.12 h8ffe710_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_6
    - vs2015_runtime 14.29.30037 h902a5da_6
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
  run:
    - click >=7.*
    - h11 >=0.8
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
test:
  commands:
    - pip check
    - uvicorn --help
  imports:
    - uvicorn
  requires:
    - pip
about:
  description: 'Uvicorn is a lightning-fast ASGI server implementation,

    using [uvloop](https://github.com/MagicStack/uvloop) and

    [httptools](https://github.com/MagicStack/httptools).

    '
  dev_url: https://github.com/encode/uvicorn
  doc_url: https://www.uvicorn.org/
  home: https://github.com/encode/uvicorn
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: The lightning-fast ASGI server.
extra:
  copy_test_source_files: true
  feedstock-name: uvicorn
  final: true
  recipe-maintainers:
    - carlodri
    - ocefpaf
    - xhochy
