# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug  9 14:00:44 2022
# ------------------------------------------------

package:
  name: anyio
  version: 3.6.1
source:
  - folder: dist
    sha256: 413adf95f93886e442aea925f3ee43baa5a765a64a0f52c6081894f9992fdd0b
    url: https://pypi.io/packages/source/a/anyio/anyio-3.6.1.tar.gz
  - folder: src
    sha256: 8e09cf634e7877741fa760b93fb46c352f888d7d3b5a8c9f2d60ca1031f03e42
    url: https://github.com/agronholm/anyio/archive/3.6.1.tar.gz
build:
  noarch: python
  number: '1'
  script: cd dist && /home/conda/feedstock_root/build_artifacts/anyio_1660053721269/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv --no-deps
  string: pyhd8ed1ab_1
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.6.15 ha878542_0
    - importlib-metadata 4.11.4 py310hff52083_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnsl 2.0.0 h7f98852_0
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.12 h166bdaf_2
    - ncurses 6.3 h27087fc_1
    - openssl 3.0.5 h166bdaf_1
    - packaging 21.3 pyhd8ed1ab_0
    - pip 22.2.2 pyhd8ed1ab_0
    - pyparsing 3.0.9 pyhd8ed1ab_0
    - python 3.10.5 ha86cf86_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1.2 h0f457ee_0
    - setuptools 63.4.2 py310hff52083_0
    - setuptools-scm 7.0.5 pyhd8ed1ab_0
    - sqlite 3.39.2 h4ff8645_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - typing-extensions 4.3.0 hd8ed1ab_0
    - typing_extensions 4.3.0 pyha770c72_0
    - tzdata 2022a h191b570_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zipp 3.8.1 pyhd8ed1ab_0
    - zlib 1.2.12 h166bdaf_2
  run:
    - idna >=2.8
    - python >=3.7
    - sniffio >=1.1
    - typing_extensions
  run_constrained:
    - trio >=0.16
test:
  commands:
    - pip check
  imports:
    - anyio
  requires:
    - coverage >=4.5
    - hypothesis >=4.0
    - mock >=4
    - pip
    - pytest >=6.0
    - pytest-cov
    - pytest-mock >=3.6.1
    - toml
    - trio
    - trustme
    - uvloop
  source_files:
    - src/pyproject.toml
    - src/tests
about:
  doc_source_url: https://github.com/agronholm/anyio/tree/3.6.1/docs
  doc_url: https://anyio.readthedocs.io
  home: https://github.com/agronholm/anyio
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE
  summary: High level compatibility layer for multiple asynchronous event loop implementations
    on Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CJ-Wright
    - bollwyvl
