# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Aug 12 06:36:09 2022
# ------------------------------------------------

package:
  name: pydantic
  version: 1.9.2
source:
  sha256: 8cb0bc509bfb71305d7a59d00163d5f9fc4530f0881ea32c74ff4f74c85f3d3d
  url: https://pypi.io/packages/source/p/pydantic/pydantic-1.9.2.tar.gz
build:
  number: '0'
  script: D:\\bld\\pydantic_1660286609753\\_h_env\\python.exe -m pip install . --no-deps
    --ignore-installed -vv
  string: py38h294d835_0
requirements:
  build:
    - vs2017_win-64 19.16.27033 hb90652a_6
    - vswhere 3.0.3 h57928b3_0
  host:
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2022.6.15 h5b45459_0
    - cython 0.29.32 py38h885f38d_0
    - libffi 3.4.2 h8ffe710_5
    - libzlib 1.2.12 h8ffe710_2
    - openssl 3.0.5 h8ffe710_1
    - pip 22.2.2 pyhd8ed1ab_0
    - python 3.8.13 hcf16a7b_0_cpython
    - python_abi 3.8 2_cp38
    - setuptools 64.0.0 py38haa244fe_0
    - sqlite 3.39.2 h8ffe710_0
    - tk 8.6.12 h8ffe710_0
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_6
    - vs2015_runtime 14.29.30037 h902a5da_6
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.5 h62dcd97_1
  run:
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - typing-extensions >=3.7.4.3
    - vc >=14.1,<15
    - vs2015_runtime >=14.16.27033
test:
  imports:
    - pydantic
about:
  description: 'Data validation and settings management using python type hinting.

    See documentation <https://pydantic-docs.helpmanual.io> for more details.

    '
  dev_url: https://github.com/samuelcolvin/pydantic
  doc_url: https://pydantic-docs.helpmanual.io
  home: https://github.com/samuelcolvin/pydantic
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Data validation and settings management using python type hinting
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dgasmith
    - samuelcolvin
