# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 26 17:47:06 2022
# ------------------------------------------------

package:
  name: fastapi
  version: 0.81.0
source:
  sha256: 9dafdc41feda85ee5acf0f7dd6bcb7fd946318a6664b41fd33e33b26f666a346
  url: https://pypi.io/packages/source/f/fastapi/fastapi-0.81.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/fastapi_1661536092192/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - brotlipy 0.7.0 py310h5764c6d_1004
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2022.6.15 ha878542_0
    - certifi 2022.6.15 py310hff52083_0
    - cffi 1.15.1 py310h255011f_0
    - charset-normalizer 2.1.1 pyhd8ed1ab_0
    - cryptography 37.0.4 py310h597c629_0
    - docutils 0.19 py310hff52083_0
    - flit 3.7.1 pyhd8ed1ab_0
    - flit-core 3.7.1 pyhd8ed1ab_0
    - idna 3.3 pyhd8ed1ab_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.4.2 h7f98852_5
    - libgcc-ng 12.1.0 h8d9b700_16
    - libgomp 12.1.0 h8d9b700_16
    - libnsl 2.0.0 h7f98852_0
    - libsqlite 3.39.2 h753d276_1
    - libuuid 2.32.1 h7f98852_1000
    - libzlib 1.2.12 h166bdaf_2
    - ncurses 6.3 h27087fc_1
    - openssl 1.1.1q h166bdaf_0
    - pip 22.2.2 pyhd8ed1ab_0
    - pycparser 2.21 pyhd8ed1ab_0
    - pyopenssl 22.0.0 pyhd8ed1ab_0
    - pysocks 1.7.1 py310hff52083_5
    - python 3.10.6 h582c2e5_0_cpython
    - python_abi 3.10 2_cp310
    - readline 8.1.2 h0f457ee_0
    - requests 2.28.1 pyhd8ed1ab_0
    - setuptools 65.3.0 py310hff52083_0
    - tk 8.6.12 h27826a3_0
    - tomli 2.0.1 pyhd8ed1ab_0
    - tomli-w 1.0.0 pyhd8ed1ab_0
    - tzdata 2022c h191b570_0
    - urllib3 1.26.11 pyhd8ed1ab_0
    - wheel 0.37.1 pyhd8ed1ab_0
    - xz 5.2.6 h166bdaf_0
  run:
    - pydantic >=1.6.2,!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0
    - python >=3.6.1
    - starlette =0.19.1
test:
  imports:
    - fastapi
    - fastapi.dependencies
    - fastapi.middleware
    - fastapi.openapi
    - fastapi.security
about:
  dev_url: https://github.com/tiangolo/fastapi
  doc_url: https://github.com/tiangolo/fastapi
  home: https://github.com/tiangolo/fastapi
  license: MIT
  license_file: LICENSE
  summary: FastAPI framework, high performance, easy to learn, fast to code, ready
    for production
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dhirschfeld
    - synapticarbors
    - tiangolo
